### ISSUE TITLE
25B ABV is wrong

### ISSUE THREAD

**Issue by JulienCassignol** [seth-k/BJCP-styles-XML#5]
Hey there,

25B ABV is wrong. It's 3.5-5 and should be higher (8.5 according to official BJCP if I'm not mistaken).

Cheers,

**Comment by seth-k** [comment]
Looks like 25B Saison is unique. It has multiple entries for ABV and SRM. Only the first ones were extracted. Also seems to be the only style with this issue.

SRM:
 5 – 14 (pale)
 15 – 22 (dark)

ABV: 
3.5 – 5.0% (table)
5.0 – 7.0% (standard)
7.0 – 9.5% (super)

**Comment by seth-k** [comment]
Merged a fix by giving the giving the ABV and SRM the full range and noting in exceptions the sub-style ranges.
